FROM python:3.9-slim

ENV POETRY_VERSION=1.1.14

COPY ./model /code

RUN apt-get update && apt-get install -y build-essential python-dev

WORKDIR /code

RUN pip install --upgrade pip
RUN pip install poetry==${POETRY_VERSION}
RUN poetry export -f requirements.txt --without-hashes --output requirements.txt
RUN pip install --no-cache -r requirements.txt
RUN pip install -e .